dependencies {
	compileOnly project(":apps:client-extension:client-extension-api")
	compileOnly project(":apps:client-extension:client-extension-type-api")
	compileOnly project(":apps:frontend-token:frontend-token-definition-api")

	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}